Repository JoinColony/colonySDK, pull requests merged in 2019-05, with the labels that each got.

#104 fix broken links in colonystarter pages
  docs/_CLI_ColonyCLI.md
  docs/_Docs_Overview.md
  docs/_Examples_ColonyExample.md
  docs/_Examples_ColonyExampleAngular.md
  docs/_Examples_ColonyExampleReact.md
  docs/_Starters_ColonyStarter.md
  docs/_Starters_ColonyStarterAngular.md
  docs/_Starters_ColonyStarterContract.md
  docs/_Starters_ColonyStarterReact.md
  yarn.lock
Labels: documentation, ready to merge

#108 Add domainId when removing admin in colony-example-react
  packages/colony-example-react/src/actions/adminActions.jsx
Labels: bug

#110 Fix colony-setup script in colony-example-angular
  docs/_Examples_ColonyExample.md
  docs/_Examples_ColonyExampleAngular.md
  docs/_Examples_ColonyExampleReact.md
  docs/_Starters_ColonyStarter.md
  docs/_Starters_ColonyStarterAngular.md
  docs/_Starters_ColonyStarterContract.md
  docs/_Starters_ColonyStarterReact.md
  packages/colony-cli/README.md
  packages/colony-example-angular/README.md
  packages/colony-example-angular/package.json
  packages/colony-example-react/README.md
  packages/colony-example/README.md
  packages/colony-starter-angular/README.md
  packages/colony-starter-contract/README.md
  packages/colony-starter-react/README.md
  packages/colony-starter/README.md
Labels: bug

#111 Update master with latest from develop
  docs/_Examples_ColonyExample.md
  docs/_Examples_ColonyExampleAngular.md
  docs/_Examples_ColonyExampleReact.md
  docs/_Starters_ColonyStarter.md
  docs/_Starters_ColonyStarterAngular.md
  docs/_Starters_ColonyStarterContract.md
  docs/_Starters_ColonyStarterReact.md
  packages/colony-cli/README.md
  packages/colony-example-angular/README.md
  packages/colony-example-angular/package.json
  packages/colony-example-react/README.md
  packages/colony-example-react/package.json
  packages/colony-example-react/src/actions/adminActions.jsx
  packages/colony-example/README.md
  packages/colony-starter-angular/README.md
  packages/colony-starter-contract/README.md
  packages/colony-starter-react/README.md
  packages/colony-starter/README.md
Labels: maintenance
